# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pro_uuid', models.CharField(default='', max_length=125, verbose_name='uuid')),
                ('user', models.ManyToManyField(blank=True, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '产品参与',
                'verbose_name_plural': '产品参与',
                'db_table': 'tb_prodpartner',
            },
        ),
    ]
