# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-23 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200330_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uuid_ascii_code', models.CharField(default='', max_length=11, verbose_name='升级码')),
                ('product_project_num', models.CharField(default='', max_length=64, verbose_name='项目号')),
                ('product_name', models.CharField(default='', max_length=32, verbose_name='产品型号')),
                ('product_series', models.CharField(default='', max_length=32, verbose_name='产品系列')),
                ('offered_by', models.CharField(default='Aputure', max_length=32, verbose_name='公司')),
                ('product_updated_admin_name', models.CharField(default='', max_length=32, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '固件产品',
                'verbose_name_plural': '固件产品',
                'db_table': 'tb_firmware_product',
            },
        ),
    ]
