# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_firmwareproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmwareproduct',
            name='product_series',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='产品系列'),
        ),
        migrations.AlterField(
            model_name='firmwareproduct',
            name='uuid_ascii_code',
            field=models.CharField(default='user_submit', max_length=11, verbose_name='升级码'),
        ),
    ]
