# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-05-29 02:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20200529_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmwareproduct',
            name='submit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_submit', to=settings.AUTH_USER_MODEL, verbose_name='提交人员'),
        ),
    ]
