# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_department_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
    ]
