# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_department_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dispaly_name',
            field=models.CharField(default='', max_length=125, verbose_name='展示名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='用户角色'),
        ),
    ]
