# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200307_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dispaly_name',
            new_name='display_name',
        ),
    ]
