# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-16 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200307_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
