# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200316_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/home/jack/development/项目/dj_iot/mediauser_avatar/default.jpg', null=True, upload_to='user_avatar/', verbose_name='头像'),
        ),
    ]
