# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-16 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200316_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default.jpg', null=True, upload_to='user_avatar/%Y/%m/%d/%h_%m_%s', verbose_name='头像'),
        ),
    ]
