# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-17 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200316_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sidus_avatar',
            field=models.CharField(default='', max_length=125, verbose_name='Sidus头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default.jpg', null=True, upload_to='user_avatar/%Y/%m/%d/%s', verbose_name='头像'),
        ),
    ]
