# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-17 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200317_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sidus_avatar',
            field=models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='Sidus头像'),
        ),
    ]
