# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-18 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=125, unique=True, verbose_name='角色名称'),
        ),
    ]
