# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200319_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.CharField(blank=True, max_length=125, null=True, verbose_name='部门名称')),
                ('role_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='角色名称')),
                ('status', models.IntegerField(blank=True, default=0, null=True, verbose_name='status')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_info', to='user.Department', verbose_name='user')),
            ],
            options={
                'verbose_name': '信息',
                'verbose_name_plural': '信息',
                'db_table': 'tb_Requestinfo',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(blank=True, db_index=True, default=None, null=True, related_name='users', to='user.Department', verbose_name='部门'),
        ),
    ]
