# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20200326_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='用户角色'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ManyToManyField(blank=True, db_index=True, null=True, related_name='users', to='user.Department', verbose_name='部门'),
        ),
    ]
