# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-27 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200326_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar/%Y/%m/%d/%s', verbose_name='头像'),
        ),
    ]
