# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 04:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinfo',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_info', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
