# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-09 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200328_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_color',
            field=models.CharField(blank=True, default='', max_length=125, null=True, verbose_name='头像颜色'),
        ),
    ]
