# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLueTooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sidus_id', models.IntegerField(blank=True, null=True, verbose_name='id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
