# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BLueTooth',
        ),
    ]
